name: Work

on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    name: Ty Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: map.ovpn
      - name: Check if connected
        run: docker run -d -p 5566:5901 consol/rocky-xfce-vnc && sleep 1h
        
